using System.Collections.Generic;
using TMPro;
using UnityEngine;

public class TimeSignature : Label<(int, int)>
{
    public static HashSet<int> SelectedTSEvents { get; set; }
    bool selectionActionsEnabled = false;

    public override HashSet<int> GetSelectedEvents()
    {
        return SelectedTSEvents;
    }

    void Awake()
    {
        inputMap = new();
        inputMap.Enable();

        if (!selectionActionsEnabled)
        {
            inputMap.Charting.Delete.performed += x => DeleteSelection();
            inputMap.Charting.Copy.performed += x => CopySelection();
            inputMap.Charting.Paste.performed += x => PasteSelection();
            selectionActionsEnabled = true;
        }
    }
    public override SortedDictionary<int, (int, int)> GetEventClipboard()
    {
        return tsClipboard;
    }

    public override SortedDictionary<int, (int, int)> GetTargetEventSet()
    {
        return SongTimelineManager.TimeSignatureEvents;
    }

    SortedDictionary<int, (int, int)> tsClipboard;

    public override void HandleManualEndEdit(string newVal)
    {
        SongTimelineManager.TimeSignatureEvents[Tick] = ProcessUnsafeTSString(newVal);

        BeatlinePreviewer.editMode = true;
        ConcludeManualEdit();
    }
    
    /// <summary>
    /// Take a TS string generated by user and turn it into a dictionary safe tuple
    /// </summary>
    /// <param name="newTS"></param>
    /// <returns></returns>
    (int, int) ProcessUnsafeTSString(string newTS)
    {
        var currentTS = SongTimelineManager.TimeSignatureEvents[Tick];
        var seperatedTS = newTS.Split("/");
        if (seperatedTS.Length == 1) return currentTS;

        if (!int.TryParse(seperatedTS[0], out int num)) return currentTS; // dunno why this would fail but i have a feeling

        if (!int.TryParse(seperatedTS[1], out int denom)) return currentTS;
        // TS denoms are only valid as a power of 2 (1, 2, 4, 8, etc.)
        if (!(denom != 0 && (denom & (denom - 1)) == 0)) return currentTS; // taken from https://stackoverflow.com/questions/600293/how-to-check-if-a-number-is-a-power-of-2 

        return (num, denom);
    }
}