using System.Collections.Generic;
using UnityEngine;

public class TSLabel : Label<TSData>, IPoolable
{
    #region Event Sets
    public override EventData<TSData> GetEventData() => Chart.SyncTrackInstrument.tsEventData;

    public override SortedDictionary<int, TSData> GetEventSet() => TimeSignature.Events;

    public override void SetEvents(SortedDictionary<int, TSData> newEvents) => TimeSignature.SetEvents(newEvents);

    public override MoveData<TSData> GetMoveData() => Chart.SyncTrackInstrument.tsMoveData;
    public override void RefreshEvents() => TSLane.instance.UpdateEvents();
    public override IPreviewer EventPreviewer => TSPreviewer.instance;
    public override IInstrument parentInstrument => Chart.SyncTrackInstrument;
    public Coroutine destructionCoroutine { get; set; }

    #endregion

    #region Event Handlers
    protected override bool tick0Immune { get; set; } = true;

    public override void HandleManualEndEdit(string newVal)
    {
        TimeSignature.Events[Tick] = ProcessUnsafeTSString(newVal);

        ConcludeManualEdit();
    }

    #endregion

    public override void SustainSelection() { return; }
    public override void CompleteSustain()
    {
        return;
    }

    #region Conversions

    /// <summary>
    /// Take a TS string generated by user and turn it into a dictionary safe tuple
    /// </summary>
    /// <param name="newTS"></param>
    /// <returns></returns>
    TSData ProcessUnsafeTSString(string newTS)
    {
        var currentTS = TimeSignature.Events[Tick];
        var seperatedTS = newTS.Split("/");
        if (seperatedTS.Length == 1) return currentTS;

        if (!int.TryParse(seperatedTS[0], out int num)) return currentTS; // dunno why this would fail but i have a feeling

        if (!int.TryParse(seperatedTS[1], out int denom)) return currentTS;
        // TS denoms are only valid as a power of 2 (1, 2, 4, 8, etc.)
        if (!(denom != 0 && (denom & (denom - 1)) == 0)) return currentTS; // taken from https://stackoverflow.com/questions/600293/how-to-check-if-a-number-is-a-power-of-2 

        return new TSData(num, denom);
    }

    public override string ConvertDataToPreviewString()
    {
        return $"{TimeSignature.Events[Tick].Numerator} / {TimeSignature.Events[Tick].Denominator}";
    }

    #endregion
}